### ISSUE TITLE
Add T-shape window layout

### ISSUE THREAD

**Issue by timoweave** [davazp/graphql-mode#10]
# Add T-shape window Layout

1. add T-shape layout similar to the graphiql ui interface
1. keep the user layout if those `*GraphQL*` or `variables.json` is already layout-ed.

for example:
![screen shot 2017-09-27 at 9 36 23 am](https://user-images.githubusercontent.com/13225610/30925651-6c86436c-a367-11e7-99c0-a9672017d11e.png)

**Comment by davazp** [comment]
How do you suggest doing this?  A command to setup this window configuration like

`graphql-set-window-layout` ?

**Comment by timoweave** [comment]
I think something like that as the first try. Need to figure out how to layout  the buffer to the right "place", instead of `split-window-*` and `other-window-*`

`
(defun graphql-send-query ()
  (interactive)
  (let ((url (or graphql-url (read-string "GraphQL URL: " ))))
    (let ((graphql-url url))
      (let* ((query (buffer-substring-no-properties (point-min) (point-max)))
             (operation (graphql-current-operation))
             (variables (graphql-current-variables var))
             (response-buffer (get-buffer-create graphql-response-buffer-name))
             (response (graphql--query query operation variables)))
        (with-current-buffer response-buffer
          (erase-buffer)
          (when (fboundp 'json-mode)
            (json-mode))
          (insert response)
          (json-pretty-print-buffer))
        (graphql-window-layout var graphql-response-buffer-name)))

    ;; If the query was successful, then save the value of graphql-url
    ;; in the current buffer (instead of the introduced local
    ;; binding).
    (setq graphql-url url)
    nil))

(defun graphql-window-layout (variables-filename response-name)
  "Arrange window in T-layout among queries, variables, and response buffers."
  (let ((response-buffer (get-buffer-create response-name))
        (variables-buffer (get-buffer-create (find-file-noselect variables-filename))))
    (when (null (or (get-buffer-window response-buffer)
                    (get-buffer-window variables-buffer)))
      (delete-other-windows)
      (split-window-right)
      (switch-to-buffer-other-window response-buffer)
      (other-window 1)
      (split-window-below)
      (switch-to-buffer-other-window variables-buffer)
      (split-window-below)
      (other-window 4)
      (delete-window))))
`

**Comment by timoweave** [comment]
quiet for too long...
