### ISSUE TITLE
Whitespace-mode support

### ISSUE THREAD

**Issue by 1bharat** [davazp/graphql-mode#20]
I have whitespace-mode enabled.

A typical file will look like this
<img width="838" alt="screen shot 2018-12-16 at 8 55 16 pm" src="https://user-images.githubusercontent.com/6837979/50052213-fcc34300-0174-11e9-94ec-e968febc3549.png">

But in graphql-mode, it looks like this
<img width="700" alt="screen shot 2018-12-16 at 8 56 43 pm" src="https://user-images.githubusercontent.com/6837979/50052237-22e8e300-0175-11e9-839f-c0aa73d89408.png">

Spaces are themed to a different color somehow. This is happening only in graphql-mode.

**Comment by davazp** [comment]
The problem seems to be in this rule font-lock rule:

https://github.com/davazp/graphql-mode/blob/next/graphql-mode.el#L346-L347

But I am not familiar with `whitespace-mode`. It would be great if someone can help with this 🙂
