### ISSUE TITLE
Could I define graphql url in .graphql text file?

### ISSUE THREAD

**Issue by liuchong** [davazp/graphql-mode#21]
Very nice package, on question is that could I define graphql url in .graphql text file,
say just add a line like `# graphql_url = "http://127.0.0.1:graphql"` directly in the beginning of current file or buffer?

Thanks!

**Comment by davazp** [comment]
You can use [file variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables) to do that. For example, write:

```graphql
# Local Variables:
# graphql-url: "test"
# End:
```

at the bottom of the file. Emacs will ask you if you want to set that variable for that file, warning that it could be unsafe to do so. If you approve it, it will set it.

**Comment by liuchong** [comment]
@davazp Thanks!

**Comment by liuchong** [comment]
```
# Local Variables:
# graphql-url: "http://127.0.0.1:3000/graphql"
# End:
```

I've added these above lines at the buttom of my .graphql file, but when I type C-c C-c, emacs shows an error message `Wrong type argument: stringp, nil`

**Comment by davazp** [comment]
You have to revisit the file for the variable to take effect. Try killing the buffer and reopening the file.

**Comment by liuchong** [comment]
Yes, I've closed the file and re-opened it. It asked `y`, `n`, `!` and I anwserd `y`.
It does not ask me to set graphql-url any more, but just raise the error message.

**Comment by davazp** [comment]
Ok, my mistake. There was an issue in the command.  I have fixed it now. 👍 thanks for reporting it.

**Comment by liuchong** [comment]
It works now, thanks! :cat:
