### ISSUE TITLE
Add support for HTTP headers

### ISSUE THREAD

**Issue by adimit** [davazp/graphql-mode#41]
While there's an issue on auth #11, our backend's auth does not work with http basic auth, but instead you need to supply headers. I'd need to supply headers for other reasons, too.

I'm using heavier gql clients right now (e.g. graphql-playground, altair) in order to get that work done, but it would be quite awesome if we could set headers for the requests in some way.

What might be a cool feature is if the headers don't need to be saved in a file or variable, but were editable in a separate, specially named buffer, kind of like it's done in graphql-playground, as quite often, I'll even need to edit the headers.

If that's a feature you'd be interested in adding, I might open a PR, if desired.

**Comment by davazp** [comment]
> What might be a cool feature is if the headers don't need to be saved in a file or variable, but were editable in a separate, specially named buffer, kind of like it's done in graphql-playground, as quite often, I'll even need to edit the headers.

Agreed!  So we have the `graphql-extra-headers` variable right now, and this can be set by `graphql-select-endpoint`.

I think that having an editor for `graphql-extra-headers` would be nice.  It could just rely on json-mode (if installed).  And from that buffer we could optionally save the variables back into the `.graphqlconfig` file if needed.

**Comment by adimit** [comment]
I'm still thinking about how to do it best. I think the buffer could be pre-populated with the content of the current endpoint and/or `graphql-extra-headers`, if it exists? Haven't done that amount of elisp hacking yet, but I'll see if I can come up with something.

**Comment by davazp** [comment]
> I'm still thinking about how to do it best. I think the buffer could be pre-populated with the content of the current endpoint and/or graphql-extra-headers, if it exists

Yes that sounds good.  Cool, let me know if I can help with anything. 

I think a similar mechanism could later be used to edit also variables, so you aren't forced to have them in a file. So we can have some variables that are used, containing the data. Functions to load/save those variables from/to files,  and a way to edit the variables in buffers. 👍

**Comment by adimit** [comment]
Yes, editing variables would be great, but let's take it one by one!

**Comment by adimit** [comment]
We've got support for in-line editing of headers with #42 now.
