### ISSUE TITLE
Only Save URL if query succeeded

### ISSUE THREAD

**Issue by nodo** [davazp/graphql-mode#6]
Hi @davazp,

Thanks for developing `graphql-mode` 👍  I have a minor suggestion, would it be possible to cache the URL only if the query is correct?

For instance, suppose that I have a valid query, I hit `C-c C-c` but the URL I insert is malformed. Now I have to re-load `graphql-mode` in order to re-insert a correct URL.

What do you think?

Thanks,
Andrea

**Comment by davazp** [comment]
Sure I can do that. Thanks for the suggestion. 👍 

In the mean time, if you are working with a single server most of the time, you can also set the variable in your .emacs:

```emacs-lisp
(setq graphql-url "http://...")
```
