### ISSUE TITLE
Treat underscore as part of word

### ISSUE THREAD

**Issue by johnbendi** [davazp/graphql-mode#8]
Hi @davazp 

`graphql-mode` does not treat underscore as part of a word. See the following screenshot:

![emacs_graphql_syntax_highlighting_problem](https://user-images.githubusercontent.com/1025834/27515858-7d08afe2-59a5-11e7-8081-377dee2d945a.png)

Is this normal behavior?

Regards

**Comment by davazp** [comment]
Hi @johnbendi, thanks for reporting it.

It should be fixed now in master. It could take a while until it is available in MELPA.
